import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { sans } from "./fonts";
import "./globals.css";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sans.className}`}>
        <Toaster position="top-center" />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
